"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useToast } from "@/hooks/use-toast"
import { createClient } from "@/lib/supabase/client"
import { cn } from "@/lib/utils"
import { Globe, Search, Palette, ShoppingCart, Megaphone, LifeBuoy, Plus, Loader2, Trash2, Eye, EyeOff, X, Code, Smartphone, Rocket, Shield, Zap, Layout, Cpu, Heart, Layers, MessageSquare, Database, Cloud, Lock, BarChart, Target, PenTool, MousePointer2, Camera, GraduationCap, School, Pencil, FileText } from "lucide-react"

const ICON_LIST = [
  { name: "Globe", icon: Globe }, { name: "Search", icon: Search }, { name: "Palette", icon: Palette }, { name: "ShoppingCart", icon: ShoppingCart }, { name: "Megaphone", icon: Megaphone }, { name: "LifeBuoy", icon: LifeBuoy }, { name: "Code", icon: Code }, { name: "Smartphone", icon: Smartphone }, { name: "Rocket", icon: Rocket }, { name: "Shield", icon: Shield }, { name: "Zap", icon: Zap }, { name: "Layout", icon: Layout }, { name: "Cpu", icon: Cpu }, { name: "Heart", icon: Heart }, { name: "Layers", icon: Layers }, { name: "MessageSquare", icon: MessageSquare }, { name: "Database", icon: Database }, { name: "Cloud", icon: Cloud }, { name: "Lock", icon: Lock }, { name: "BarChart", icon: BarChart }, { name: "Target", icon: Target }, { name: "PenTool", icon: PenTool }, { name: "MousePointer2", icon: MousePointer2 }, { name: "Camera", icon: Camera }, { name: "GraduationCap", icon: GraduationCap }, { name: "School", icon: School }
]
const ICON_MAP: Record<string, any> = Object.fromEntries(ICON_LIST.map(item => [item.name, item.icon]))
interface Service { id: string; title: string; description: string; icon_name: string; status: "active" | "inactive"; sort_order: number }

export default function AdminServicesPage() {
  const [services, setServices] = useState<Service[]>([]), [isLoading, setIsLoading] = useState(true), [isSaving, setIsSaving] = useState(false), [showForm, setShowForm] = useState(false), [editingId, setEditingId] = useState<string | null>(null)
  const [formData, setFormData] = useState({ title: "", description: "", icon_name: "Globe" })
  const { toast } = useToast(), supabase = createClient()

  const fetchServices = async () => { const { data, error } = await supabase.from("services").select("*").order("sort_order", { ascending: true }); if (error) toast({ title: "Error", description: "Failed to load services.", variant: "destructive" }); else setServices((data || []) as Service[]); setIsLoading(false) }
  useEffect(() => { fetchServices() }, [])
  const closeForm = () => { setShowForm(false); setEditingId(null); setFormData({ title: "", description: "", icon_name: "Globe" }) }
  const handleSave = async (e: React.FormEvent) => { e.preventDefault(); setIsSaving(true); try { if (editingId) { const { data, error } = await supabase.from("services").update(formData).eq("id", editingId).select(); if (error) throw error; if (data?.[0]) setServices(services.map(s => s.id === editingId ? data[0] as Service : s)); toast({ title: "Service updated successfully" }) } else { const { data, error } = await supabase.from("services").insert([{ ...formData, status: "active", sort_order: services.length }]).select(); if (error) throw error; if (data?.[0]) setServices([...services, data[0] as Service]); toast({ title: "Service added successfully" }) } closeForm() } catch (error: any) { toast({ title: "Error", description: error.message, variant: "destructive" }) } finally { setIsSaving(false) } }
  const handleEdit = (service: Service) => { setEditingId(service.id); setFormData({ title: service.title, description: service.description, icon_name: service.icon_name }); setShowForm(true); window.scrollTo({ top: 0, behavior: "smooth" }) }
  const toggleStatus = async (id: string, current: string) => { const next = current === "active" ? "inactive" : "active"; const { error } = await supabase.from("services").update({ status: next }).eq("id", id); if (error) toast({ title: "Error", variant: "destructive" }); else { setServices(services.map(s => s.id === id ? { ...s, status: next as Service["status"] } : s)); toast({ title: "Status updated" }) } }
  const deleteService = async (id: string) => { if (!confirm("Are you sure? This service will be removed from your homepage.")) return; const { error } = await supabase.from("services").delete().eq("id", id); if (error) toast({ title: "Error", variant: "destructive" }); else { setServices(services.filter(s => s.id !== id)); toast({ title: "Service deleted" }) } }

  if (isLoading) return <div className="h-[400px] grid place-items-center"><Loader2 className="w-8 h-8 text-teal animate-spin" /></div>
  return <div className="space-y-8">
    <div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold tracking-tight text-navy">Service Offerings</h1><p className="text-gray-600 mt-1">Manage homepage services and their detail pages</p></div>{!showForm && <Button onClick={() => setShowForm(true)} className="bg-teal text-navy font-bold hover:bg-teal/90 gap-2"><Plus className="w-4 h-4" />Add Service</Button>}</div>
    {showForm && <Card className="border-teal/30 bg-white relative overflow-hidden rounded-[24px] shadow-xl shadow-teal/5"><button onClick={closeForm} className="absolute top-4 right-4 text-gray-400 hover:text-navy z-10"><X className="w-5 h-5" /></button><CardHeader><CardTitle>{editingId ? "Edit Service" : "Add New Service"}</CardTitle></CardHeader><CardContent><form onSubmit={handleSave} className="space-y-8"><div className="grid sm:grid-cols-2 gap-8"><div className="space-y-6"><div className="space-y-2"><Label>Service Title</Label><Input required value={formData.title} onChange={e => setFormData({ ...formData, title: e.target.value })} placeholder="e.g. Web Development" /></div><div className="space-y-2"><Label>Description</Label><textarea required className="w-full min-h-[120px] rounded-xl border border-input bg-background px-4 py-3 text-sm" value={formData.description} onChange={e => setFormData({ ...formData, description: e.target.value })} placeholder="Short service description" /></div></div><div className="space-y-3"><Label>Select Icon</Label><div className="grid grid-cols-6 gap-2 p-4 bg-gray-50 rounded-2xl border border-black/5 max-h-[240px] overflow-y-auto">{ICON_LIST.map(item => <button key={item.name} type="button" onClick={() => setFormData({ ...formData, icon_name: item.name })} className={cn("aspect-square rounded-xl flex items-center justify-center", formData.icon_name === item.name ? "bg-teal text-navy scale-110 shadow-lg" : "bg-white text-gray-400 hover:text-navy border border-black/[0.03]")}><item.icon className="w-5 h-5" /></button>)}</div></div></div><div className="flex justify-end gap-3"><Button variant="ghost" type="button" onClick={closeForm}>Cancel</Button><Button type="submit" disabled={isSaving} className="bg-navy px-8 font-bold">{isSaving && <Loader2 className="w-4 h-4 animate-spin mr-2" />}{editingId ? "Update Service" : "Create Service"}</Button></div></form></CardContent></Card>}
    {services.length === 0 ? <Card className="p-12 text-center border-dashed rounded-[24px]"><p className="text-gray-500 mb-4">No services found.</p><Button variant="outline" onClick={() => setShowForm(true)}>Add Service</Button></Card> : <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{services.map(service => { const Icon = ICON_MAP[service.icon_name] || Globe; return <Card key={service.id} className={cn("group rounded-[24px] shadow-sm", service.status === "inactive" && "opacity-60")}><CardHeader className="flex flex-row items-center justify-between pb-2"><div className="w-10 h-10 rounded-lg bg-teal/10 flex items-center justify-center"><Icon className="w-5 h-5 text-teal" /></div><span className={cn("text-[11px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full", service.status === "active" ? "bg-teal/10 text-teal" : "bg-gray-100 text-gray-400")}>{service.status}</span></CardHeader><CardContent><CardTitle className="text-[18px] mb-2">{service.title}</CardTitle><p className="text-[14px] text-gray-500 line-clamp-2 mb-6 h-10">{service.description}</p><div className="flex gap-2"><Button variant="outline" size="sm" className="flex-1 rounded-lg font-bold" onClick={() => handleEdit(service)}><Pencil className="w-3.5 h-3.5 mr-2" />Edit basics</Button><Button variant="outline" size="sm" className="rounded-lg font-bold" asChild><Link href={`/admin/services/${service.id}`}><FileText className="w-3.5 h-3.5 mr-2" />Details</Link></Button><Button variant="ghost" size="sm" onClick={() => toggleStatus(service.id, service.status)}>{service.status === "active" ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</Button><Button variant="ghost" size="sm" className="text-gray-400 hover:text-coral" onClick={() => deleteService(service.id)}><Trash2 className="w-4 h-4" /></Button></div></CardContent></Card> })}</div>}
  </div>
}
